---
name: Checks

on:
  push:
    branches: [puppet-sonal]
  pull_request:
    branches: [puppet-sonal]

permissions:
  contents: read

jobs:
  checks:
    name: ${{ matrix.cfg.check }}
    strategy:
      matrix:
        cfg:
          - {check: rubocop, os: self-hosted, ruby: '3.1'}
          - {check: warnings, os: self-hosted, ruby: '3.1'}

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ruby version ${{ matrix.cfg.ruby }}
        run: |
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          if [ ! -f "/opt/runner/_work/_tool/Ruby/3.1/s390x.complete" ]; then
            ruby-build 3.1 /opt/runner/_work/_tool/Ruby/3.1/s390x
            touch /opt/runner/_work/_tool/Ruby/3.1/s390x.complete
          fi

      - name: Update rubygems and install gems
        run: |
          gem update --system --silent --no-document
          bundle config set without packaging documentation
          bundle install --jobs 4 --retry 3

      - name: Run ${{ matrix.cfg.check }} check
        run: bundle exec rake ${{ matrix.cfg.check }}
